targets:
  $default:
    sources:
      - lib/**
      - swaggers/**
      - swaggers2/**
      - swagger_examples/**
      - $package$
    builders:
      swagger_dart_code_generator:
        options:
          with_base_url: true
          with_converter: true
          use_required_attribute_for_headers: true
          ignore_headers: true
          use_default_null_for_lists: false
          use_inheritance: false
          build_only_models: false
          use_path_for_request_names: true
          include_if_null:
            enabled: true
            value: false
          enums_case_sensitive: true
          input_folder: 'lib/'
          output_folder: 'lib/generated_code/'